import Head from 'next/head';
import CallbackForm from '~/components/CallbackForm/CallbackForm';

export default function GetAQuote()
{
  return (
    <>
      <Head>
        <title>Get a quote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CallbackForm />
      </main>
    </>
  );
}
