import Head from 'next/head';
import HomePage from '~/components/HomePage';
import Background from '~/components/Background';
import LampLightAnimation from '~/components/Background/LampLightAnimation/';
import LampLigth from '~/components/Background/LampLight';
import House from '~/components/Background/House';
import Kitchen from '~/components/Background/Kitchen';
import Bath from '~/components/Background/Bath';
import Thorfer from '~/components/Background/Thorfer';
import useWindowWidth from '~/hooks/useWindowWidth';

export default function Home() {
  const windowWidth = useWindowWidth();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <HomePage />
      </main>
      <Background>
        <LampLightAnimation
          top={ windowWidth >= 1440 ? '-20%' : windowWidth >= 768 ? '-27%' : '-31%' }
          left={ windowWidth >= 1440 ? '30%' : windowWidth >= 768 ? '56%' : '50%' }
        />
        <LampLigth
          top={ windowWidth >= 1440 ? '-41%' : '-53%' }
          left="20%"
          delay="2.5"
        />
        <LampLigth top="-48%" left="37%" delay="3" />
        <House
          width={ windowWidth >= 1440 ? '227' : windowWidth >= 768 ? '146' : '137' }
          height={ windowWidth >= 1440 ? '227' : windowWidth >= 768 ? '146' : '110' }
          top={ windowWidth >= 1440 ? '34%' : windowWidth >= 768 ? '38%' : '38%' }
          left={ windowWidth >= 1440 ? '67%' : windowWidth >= 768 ? '14%' : '11%' }
        />
        <Kitchen
          bottom={ windowWidth <= 768 ? '15%' : '13%' }
          left={ windowWidth >= 1440 ? '20%' : windowWidth >= 768 ? '75%' : '73%' }
          width={ windowWidth >= 1440 ? '150' : windowWidth >= 768 ? '103' : '70' }
          height={ windowWidth >= 1440 ? '160' : windowWidth >= 768 ? '109' : '75' }
        />
        <Bath
          bottom={ windowWidth >= 1440 ? '20%' : windowWidth >= 768 ? '5%' : '10%' }
          left={ windowWidth >= 1440 ? '87%' : windowWidth >= 768 ? '27%' : '15%' }
          width={ windowWidth >= 1440 ? '160' : '104' }
          height={ windowWidth >= 1440 ? '146' : '99' }
        />
        {windowWidth >= 768
          ? <Thorfer top="62%" left="55%" delay="7" />
          : null}
      </Background>
    </>
  );
}
