import Head from 'next/head';
import Reviews from '~/components/Reviews/Reviews';

export default function ReviewsPage()
{
  return (
    <>
      <Head>
        <title>Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyDFWvgz9fkV8wnlzz3nsoBKDb17UjMJsv0" />
      </Head>
      <main>
        {/* <div id="map" /> */}
        <Reviews />
      </main>
    </>
  );
}
