import Head from 'next/head';
import ServicesList from '~/components/ServicesList';

export default function Home()
{
  return (
    <>
      <Head>
        <title>service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ServicesList />
      </main>
    </>
  );
}
